### ISSUE TITLE
Errors on some choices of XLSForm WHO VA 2016

### ISSUE THREAD

**Issue by paulphilimone** [SwissTPH/WHO_VA_2016#3]
Two errors on the form for choice values exceding 32characters 
   XForm Parse Warning: choice value [government_health_center_or_clinic] is too long; max. 
   XForm Parse Warning: choice value [community_based_practitionerinsystem] is too long; max.
   This error can be avoided by changing the value name

**Comment by aurdipas** [comment]
Thanks Paulo. We'll fix it for the next release

**Comment by aurdipas** [comment]
fixed on v1.5
