### ISSUE TITLE
Instrument Name

### ISSUE THREAD

**Issue by rileyhazard** [SwissTPH/WHO_VA_2016#37]
The  WHO 2016 questionnaire downloaded from the [WHO Verbal Autopsy Standards](http://www.who.int/healthinfo/statistics/verbalautopsystandards/en/) website has the filename ```08_1_WHOVA2016_v1_5_1_XLS_form_for_ODK```. [XLSForm Online](https://opendatakit.org/xlsform/) fails because of the following error:
```
    Error: The name '08_1_WHOVA2016_v1_5_1_XLS_form_for_ODK' is an invalid xml tag. 
    Names must begin with a letter, colon, or underscore, subsequent characters 
    can include numbers, dashes, and periods.
``` 
This issue can easily be fixed by renaming the file, but I would suggest removing the number from the beginning of the filename.

**Comment by aurdipas** [comment]
this has been already renamed on GitHub. Will be provided next release
