### ISSUE TITLE
Instrument XML version

### ISSUE THREAD

**Issue by rileyhazard** [SwissTPH/WHO_VA_2016#38]
The  WHO 2016 questionnaire downloaded from the [WHO Verbal Autopsy Standards](http://www.who.int/healthinfo/statistics/verbalautopsystandards/en/) website only contains the ```.xlsx``` form. I would suggest also including the ```.xml``` version so that users do not have to use [XLSForm Online](https://opendatakit.org/xlsform/) if they want to use ODK Aggregate.

**Comment by aurdipas** [comment]
this is by design. The gitHub repo is for users that want to submit an issue or for users that need to localize the instrument and anyway need to convert to xml by themselves. Users that want to use the default instrument will download it from the official WHO website page.
