### ISSUE TITLE
AGE CATEGORY FOR WHO TOOL

### ISSUE THREAD

**Issue by QollinsOchieng** [SwissTPH/WHO_VA_2016#43]
Hello guyz. According to the definition of age categories in the 2016 WHO questionnaire , child is to be upto 11 years whereas Adult is to be above 12 years. In the questionnaire age group calculation:
isChild1 -- if(${ageInDays} >27 and ${ageInDays} <=11*365.25, '1', '0')
isAdult1--if(${ageInDays} >11*365.25, '1', '0')

This makes any age begining from 11 years 1day to be categorised as Adult??? Is this intentional? I think in order to match definition as per documentation it should be;
isChild1 -- if(${ageInDays} >27 and ${ageInDays} <12*365.25, '1', '0')
isAdult1--if(${ageInDays} >=12*365.25, '1', '0')

**Comment by aurdipas** [comment]
fixed in 1.5.2 (next release)
