### ISSUE TITLE
Errors fixed in some calculation variables of XLSForm WHO

### ISSUE THREAD

**Issue by KDerra** [SwissTPH/WHO_VA_2016#44]
Dear WHO VA 2016,
In the WHO2016 XLSform, I find some errors on the calculation of some signs duration for the following variables : 
- Id10232
- Id10248
- Id10250
- Id10262
- Id10266
- ageInMonths
- ageInMonthsRemain.
I fixed by doing some modifications in my using form (see the attached file).
Kind Regards,
Karim Derra
Nanoro HDSS Manager, Burkina Faso

[ODK WHO2016 form_ corrections_made_NanoroHDSS_Apr2019_KDerra.docx](https://github.com/SwissTPH/WHO_VA_2016/files/3140232/ODK.WHO2016.form_.corrections_made_NanoroHDSS_Apr2019_KDerra.docx)

**Comment by aurdipas** [comment]
closed in 1.5.2
