### ISSUE TITLE
Question: (Id10431) Select EPI vaccines done also needs clarity for quality VA

### ISSUE THREAD

**Issue by QollinsOchieng** [SwissTPH/WHO_VA_2016#47]
Question (Id10431) Select EPI vaccines done; 

In cases where the child/neonate received only one or two of the vaccine group i.e Polio_123,  which is complete vaccination according to the age. In this case, it requires interviewers to key In "no" since not all of the vaccine group was issued which is wrong. The question needs to be reviewed and also hint corrected and Q by Q updated if there is a correction.

**Comment by aurdipas** [comment]
Clarified with the author of the issue.
There was a misunderstanding between dosages of vaccines and vaccine per se.
Issue not present

**Comment by JordanaLeitao** [comment]
Thanks Aurelio.

Best
Jordana
