### ISSUE TITLE
file names

### ISSUE THREAD

**Issue by mbratschi** [SwissTPH/WHO_VA_2016#5]
Dear Aurelio,
Not sure if I am using GitHub correctly by positing here.....
I just wanted to mention that XLS Form (https://opendatakit.org/downloads/download-info/xlsform-for-windows/) does not appear to be able to convert the Excel file to the XML questionnaire if the file name starts with a number (i.e. the way the files are currently and how they are published on the WHO website). just a minor issue.
Cheers,
Martin

**Comment by aurdipas** [comment]
I'm aware about it. I just used the same naming convention of the WHO website(as you pointed out already). Anyway the file will be renamed and re-versioned for the next release.

**Comment by mbratschi** [comment]
I hope this reply works...
Thanks for the info. Sounds good.



______________________________________________

Martin W. Bratschi, PhD
Deputy Director, Technical Implementation
Civil Registration and Vital Statistics (CRVS) Improvement Program, Data for Health Initiative

M +65 9836 6421 | E mbratschi@vitalstrategies.org<mailto:mbratschi@vitalstrategies.org> | S martinbratschi

61 Broadway, Suite 1720, New York, NY 10006, USA
146 Robinson Road, #06-01, Singapore 068909, Singapore

vitalstrategies.org<http://vitalstrategies.org>

Vital Strategies | Building Health Systems Globally | An affiliate of The Union

On 30 Jun 2017, at 8:57 PM, Aurelio <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm aware about it. I just used the same naming convention of the WHO website(as you pointed out already). Anyway the file will be renamed and re-versioned for the next release.

**Comment by aurdipas** [comment]
file updated and renamed
