### ISSUE TITLE
Id10232: error in calculation formula

### ISSUE THREAD

**Issue by jarathomas** [SwissTPH/WHO_VA_2016#52]
The current formula is:
if(${Id10232_units}='days', ${Id10232_a} div 30,${Id10232_b})

but Id10232_a is days and the Id10232 label is:

(Id10232) For how many days did the ulcer on the foot ooze pus?

The formula should be:
if(${Id10232_units}='days', ${Id10232_a},${Id10232_b} div 30)

since Id10232_b is measured in months

**Comment by aurdipas** [comment]
issue already addressed in #44
